services:
  openhands:
    build:
      context: ./
      dockerfile: ./containers/app/Dockerfile
    image: openhands:latest
    container_name: openhands-app
    command: ${CUSTOM_COMMAND:-python -m openhands.core.main --config-file /app/config.toml -f /app/prompt.txt}
    environment:
      - SANDBOX_RUNTIME_CONTAINER_IMAGE=${SANDBOX_RUNTIME_CONTAINER_IMAGE:-docker.all-hands.dev/all-hands-ai/runtime:0.21-nikolaik}
      #- SANDBOX_USER_ID=${SANDBOX_USER_ID:-1234} # enable this only if you want a specific non-root sandbox user but you will have to manually adjust permissions of openhands-state for this user
      - WORKSPACE_MOUNT_PATH=${WORKSPACE_BASE:-$PWD/workspace}
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_MODEL=litellm_proxy/${LLM_MODEL}
      - LLM_BASE_URL=http://localhost:4000
      - LOG_ALL_EVENTS=true
      - SAVE_TRAJECTORY_PATH=/saved_trajectories
      - DATA_INPUT_MOUNT=${DATA_INPUT_MOUNT}
      - DATA_OUTPUT_MOUNT=${DATA_OUTPUT_MOUNT}
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.openhands-state:/.openhands-state
      - ${WORKSPACE_BASE:-$PWD/workspace}:/opt/workspace_base
      - ${CUSTOM_OPENHANDS_CONFIG_PATH}:/app/config.toml
      - ${CUSTOM_PROMPT_FILE}:/app/prompt.txt
      - ${CUSTOM_SAVE_TRAJECTORY_PATH}:/saved_trajectories
    network_mode: host
    pull_policy: build
    stdin_open: true
    tty: true
